name: Deploy Next.js to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Match local version

      - name: Install Dependencies
        run: npm install

      - name: Build and Export Next.js
        run: npm run export

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          rm -rf /var/www/html/*
          exit
          EOF

          scp -o StrictHostKeyChecking=no -r out/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/

      - name: Restart Nginx
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl restart nginx"
